export default default_;
export function reject(arg0: any[], arg1: string, arg2: any): any[];
export function select(arg0: any[], arg1: string, arg2: any): any[];
export const sort: (...macroArgs: any[]) => any;
export function batch(arr: any, linecount: any, fillWith: any): any[][];
export function capitalize(str: any): any;
export function center(str: any, width: any): any;
declare function default_(val: any, def: any, bool: any): any;
export function dictsort(val: any, caseSensitive: any, by: any): any[][];
export function dump(obj: any, spaces: any): string;
export function escape(str: any): any;
export function safe(str: any): any;
export function first(arr: any): any;
export function forceescape(str: any): any;
export function groupby(arr: any, attr: any): {};
export function indent(str: any, width: any, indentfirst: any): any;
export function join(arr: any, del: any, attr: any): any;
export function last(arr: any): any;
declare function lengthFilter(val: any): any;
export function list(val: any): any;
export function lower(str: any): any;
export function nl2br(str: any): any;
export function random(arr: any): any;
export function rejectattr(arr: any, attr: any): any;
export function selectattr(arr: any, attr: any): any;
export function replace(str: any, old: any, new_: any, maxCount: any): any;
export function reverse(val: any): any;
export function round(val: any, precision: any, method: any): number;
export function slice(arr: any, slices: any, fillWith: any): any[];
export function sum(arr: any, attr: any, start?: number): any;
export function string(obj: any): any;
export function striptags(input: any, preserveLinebreaks: any): any;
export function title(str: any): any;
export function trim(str: any): any;
export function truncate(input: any, length: any, killwords: any, end: any): any;
export function upper(str: any): any;
export function urlencode(obj: any): any;
export function urlize(str: any, length: any, nofollow: any): any;
export function wordcount(str: any): any;
export function float(val: any, def: any): any;
declare const intFilter: (...macroArgs: any[]) => any;
export { abs, lengthFilter as length, intFilter as int, _default as d, escape as e };
//# sourceMappingURL=filters.d.ts.map